# Generated by Django 4.1.3 on 2022-11-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Columns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='ФИО')),
                ('link', models.CharField(max_length=250, verbose_name='Ссылка')),

            ],
        ),
    ]
