# Generated by Django 4.1.3 on 2022-12-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='columns',
            options={'verbose_name': 'Выпускник', 'verbose_name_plural': 'Выпускники'},
        ),
        migrations.AddField(
            model_name='columns',
            name='info',
            field=models.TextField(default='Информация отсутствует', verbose_name='Краткая информация'),
        ),
    ]
