# Generated by Django 4.1.3 on 2022-12-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns_list', '0002_alter_columns_options_columns_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columns',
            name='info',
            field=models.TextField(db_index=True, verbose_name='Краткая информация'),
        ),
        migrations.AlterField(
            model_name='columns',
            name='title',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ФИО'),
        ),
    ]
