# Generated by Django 4.1.3 on 2022-12-07 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('columns_list', '0004_alter_columns_options_columns_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columns',
            name='photo',
        ),
    ]
