# Generated by Django 4.1.3 on 2022-12-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns_list', '0005_remove_columns_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='columns',
            name='photo',
            field=models.TextField(db_index=True, default='Фото отсутствует', verbose_name='Фотография'),
        ),
    ]
